### ISSUE TITLE
production crash: access at position in production

### ISSUE THREAD

**Issue by vincenzopalazzo** [LNOpenMetrics/lnmetrics.server#50]
I noted a crash in production that looks like the following stack trace

```
Attaching to lnmetricsserver_lightningd_1
lightningd_1  | 2022-01-18T07:52:18.617059265Z panic: runtime error: slice bounds out of range [2:1]
lightningd_1  | 2022-01-18T07:52:18.617131747Z 
lightningd_1  | 2022-01-18T07:52:18.617138576Z goroutine 173937 [running]:
lightningd_1  | 2022-01-18T07:52:18.617270384Z github.com/syndtr/goleveldb/leveldb.tFiles.newIndexIterator({0xc001403f80, 0x6, 0x6}, 0xc000154cc0, 0xc0000a16e0, 0xc001fbc570, 0x0)
lightningd_1  | 2022-01-18T07:52:18.617316785Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/table.go:241 +0x2ba
lightningd_1  | 2022-01-18T07:52:18.617386208Z github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0xc0017417c0, 0x203000, 0x203000)
lightningd_1  | 2022-01-18T07:52:18.617400866Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/version.go:265 +0x125
lightningd_1  | 2022-01-18T07:52:18.617406340Z github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc0001561a0, 0x0, {0x0, 0x0, 0x5b}, 0xc001fbc570, 0xffffffffffffff)
lightningd_1  | 2022-01-18T07:52:18.617410800Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:41 +0xc6
lightningd_1  | 2022-01-18T07:52:18.617502426Z github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc0001561a0, 0xc0003cbd38, {0x0, 0x0, 0x0}, 0x3681, 0xc0007afe08, 0xc0005b7aa0)
lightningd_1  | 2022-01-18T07:52:18.617516627Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:79 +0x18b
lightningd_1  | 2022-01-18T07:52:18.617521051Z github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc0001561a0, 0xc0005b79e0, 0x5b)
lightningd_1  | 2022-01-18T07:52:18.617525825Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db.go:891 +0x14f
lightningd_1  | 2022-01-18T07:52:18.617586850Z github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb.(*database).IterateThrough(0xcf4bd0, {0xc0005b7980, 0x40eae7}, {0xc0005b79e0, 0x5b}, 0xc000462380)
lightningd_1  | 2022-01-18T07:52:18.617599520Z 	/go/lnmetrics/vendor/github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb/database_interface.go:73 +0xfd
lightningd_1  | 2022-01-18T07:52:18.617604933Z github.com/LNOpenMetrics/lnmetrics.server/internal/db.NoSQLDatabase.RawIterateThrough(...)
lightningd_1  | 2022-01-18T07:52:18.617609285Z 	/go/lnmetrics/internal/db/database_nosql.go:64
lightningd_1  | 2022-01-18T07:52:18.617739544Z github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardRatingByPeriod({0x9e7218, 0xc0001550e0}, 0xc0003cbfd0, 0xc0002ec2a0, 0xc0005a2048, 0x61e671b0, 0xfffffffffffeae80, 0x4e94914f0000, 0x65)
lightningd_1  | 2022-01-18T07:52:18.617828376Z 	/go/lnmetrics/internal/metric/metric.go:364 +0x3b5
lightningd_1  | 2022-01-18T07:52:18.617837934Z created by github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardsRatingByTimestamp
lightningd_1  | 2022-01-18T07:52:18.617919724Z 	/go/lnmetrics/internal/metric/metric.go:305 +0x1b6
```

**Comment by vincenzopalazzo** [comment]
Should be the following pr the cause https://github.com/LNOpenMetrics/lnmetrics.server/pull/47

**Comment by vincenzopalazzo** [comment]
other logs

```
Attaching to lnmetricsserver_lightningd_1
lightningd_1  | 2022-01-18T07:52:18.617059265Z panic: runtime error: slice bounds out of range [2:1]
lightningd_1  | 2022-01-18T07:52:18.617131747Z 
lightningd_1  | 2022-01-18T07:52:18.617138576Z goroutine 173937 [running]:
lightningd_1  | 2022-01-18T07:52:18.617270384Z github.com/syndtr/goleveldb/leveldb.tFiles.newIndexIterator({0xc001403f80, 0x6, 0x6}, 0xc000154cc0, 0xc0000a16e0, 0xc001fbc570, 0x0)
lightningd_1  | 2022-01-18T07:52:18.617316785Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/table.go:241 +0x2ba
lightningd_1  | 2022-01-18T07:52:18.617386208Z github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0xc0017417c0, 0x203000, 0x203000)
lightningd_1  | 2022-01-18T07:52:18.617400866Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/version.go:265 +0x125
lightningd_1  | 2022-01-18T07:52:18.617406340Z github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc0001561a0, 0x0, {0x0, 0x0, 0x5b}, 0xc001fbc570, 0xffffffffffffff)
lightningd_1  | 2022-01-18T07:52:18.617410800Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:41 +0xc6
lightningd_1  | 2022-01-18T07:52:18.617502426Z github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc0001561a0, 0xc0003cbd38, {0x0, 0x0, 0x0}, 0x3681, 0xc0007afe08, 0xc0005b7aa0)
lightningd_1  | 2022-01-18T07:52:18.617516627Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:79 +0x18b
lightningd_1  | 2022-01-18T07:52:18.617521051Z github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc0001561a0, 0xc0005b79e0, 0x5b)
lightningd_1  | 2022-01-18T07:52:18.617525825Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db.go:891 +0x14f
lightningd_1  | 2022-01-18T07:52:18.617586850Z github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb.(*database).IterateThrough(0xcf4bd0, {0xc0005b7980, 0x40eae7}, {0xc0005b79e0, 0x5b}, 0xc000462380)
lightningd_1  | 2022-01-18T07:52:18.617599520Z 	/go/lnmetrics/vendor/github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb/database_interface.go:73 +0xfd
lightningd_1  | 2022-01-18T07:52:18.617604933Z github.com/LNOpenMetrics/lnmetrics.server/internal/db.NoSQLDatabase.RawIterateThrough(...)
lightningd_1  | 2022-01-18T07:52:18.617609285Z 	/go/lnmetrics/internal/db/database_nosql.go:64
lightningd_1  | 2022-01-18T07:52:18.617739544Z github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardRatingByPeriod({0x9e7218, 0xc0001550e0}, 0xc0003cbfd0, 0xc0002ec2a0, 0xc0005a2048, 0x61e671b0, 0xfffffffffffeae80, 0x4e94914f0000, 0x65)
lightningd_1  | 2022-01-18T07:52:18.617828376Z 	/go/lnmetrics/internal/metric/metric.go:364 +0x3b5
lightningd_1  | 2022-01-18T07:52:18.617837934Z created by github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardsRatingByTimestamp
lightningd_1  | 2022-01-18T07:52:18.617919724Z 	/go/lnmetrics/internal/metric/metric.go:305 +0x1b6
lightningd_1  | 2022-01-18T07:52:18.701937459Z connect to http://localhost:8080/ for GraphQL playground2022-01-18T08:52:16.343983818Z panic: runtime error: slice bounds out of range [2:1]
lightningd_1  | 2022-01-18T08:52:16.344057367Z 
lightningd_1  | 2022-01-18T08:52:16.344064971Z goroutine 668 [running]:
lightningd_1  | 2022-01-18T08:52:16.344070488Z github.com/syndtr/goleveldb/leveldb.tFiles.newIndexIterator({0xc000e7acf0, 0x6, 0x6}, 0xc000220cc0, 0xc000021700, 0xc0011600c0, 0x0)
lightningd_1  | 2022-01-18T08:52:16.344081995Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/table.go:241 +0x2ba
lightningd_1  | 2022-01-18T08:52:16.344106911Z github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0xc0011dba90, 0x203000, 0x203000)
lightningd_1  | 2022-01-18T08:52:16.344306787Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/version.go:265 +0x125
lightningd_1  | 2022-01-18T08:52:16.345378208Z github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc00010b1e0, 0x0, {0x0, 0x0, 0x5b}, 0xc0011600c0, 0xffffffffffffff)
lightningd_1  | 2022-01-18T08:52:16.345793072Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:41 +0xc6
lightningd_1  | 2022-01-18T08:52:16.346869111Z github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc00010b1e0, 0xc00038fd38, {0x0, 0x0, 0x0}, 0x368c, 0xc000052e08, 0xc00027cfc0)
lightningd_1  | 2022-01-18T08:52:16.347325006Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:79 +0x18b
lightningd_1  | 2022-01-18T08:52:16.347829987Z github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc00010b1e0, 0xc00027cf00, 0x5b)
lightningd_1  | 2022-01-18T08:52:16.348234305Z 	/go/lnmetrics/vendor/github.com/syndtr/goleveldb/leveldb/db.go:891 +0x14f
lightningd_1  | 2022-01-18T08:52:16.349473980Z github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb.(*database).IterateThrough(0xcf4bd0, {0xc00027cd20, 0x40eae7}, {0xc00027cf00, 0x5b}, 0xc0000211d0)
lightningd_1  | 2022-01-18T08:52:16.349944233Z 	/go/lnmetrics/vendor/github.com/LNOpenMetrics/lnmetrics.utils/db/leveldb/database_interface.go:73 +0xfd
lightningd_1  | 2022-01-18T08:52:16.350056189Z github.com/LNOpenMetrics/lnmetrics.server/internal/db.NoSQLDatabase.RawIterateThrough(...)
lightningd_1  | 2022-01-18T08:52:16.350322750Z 	/go/lnmetrics/internal/db/database_nosql.go:64
lightningd_1  | 2022-01-18T08:52:16.351689914Z github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardRatingByPeriod({0x9e7218, 0xc0002210b0}, 0xc00038ffd0, 0xc0006f0078, 0xc00136a330, 0x61e67fbd, 0xfffffffffffeae80, 0x4e94914f0000, 0xc000116d80)
lightningd_1  | 2022-01-18T08:52:16.352024015Z 	/go/lnmetrics/internal/metric/metric.go:364 +0x3b5
lightningd_1  | 2022-01-18T08:52:16.352132381Z created by github.com/LNOpenMetrics/lnmetrics.server/internal/metric.calculateForwardsRatingByTimestamp
lightningd_1  | 2022-01-18T08:52:16.352566112Z 	/go/lnmetrics/internal/metric/metric.go:305 +0x1b6
lightningd_1  | 2022-01-18T08:52:16.422095270Z connect to http://localhost:8080/ for GraphQL playgroundlnmetricsserver_lightningd_1 exited with code 2

```
